# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Create on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online #produce
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      export_method: "app-store",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    upload_to_testflight
  end

  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
