name: build-ios-app
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: fastlane create_beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}